import React,{useMemo,useState} from 'react';
import Link from 'next/link';
import ContextualDivaDock from '../../../components/ContextualDivaDock';
import ContextReadingCard from '../../../components/ContextReadingCard';
import {OperationalBarChart} from '../../../components/OperationalCharts';
import {requireOSAuth} from '../../../lib/os-auth';
import {getWixLiveBrainContext} from '../../../lib/wix-live-context';
import {buildMundoCommercialProjection} from '../../../lib/mundo-commercial-projection';
import ContextOpenButton from '../../../components/ContextOpenButton';
import DataGapHeartbeat from '../../../components/DataGapHeartbeat';
import {CRM_OPERATIONAL_SNAPSHOT} from '../../../data/crm-operational-snapshot-current';

const INACTIVE=/descart|perdid|cancelad|arquivad|encerrad/i;
const norm=v=>String(v||'').trim().toLowerCase();
function normalizedDateKey(value=''){const raw=String(value||'').trim();const br=raw.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(br)return`${br[3]}-${br[2]}-${br[1]}`;const iso=raw.match(/^(\d{4})-(\d{2})-(\d{2})/);return iso?`${iso[1]}-${iso[2]}-${iso[3]}`:null}
function saoPauloDateKey(date=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return`${map.year}-${map.month}-${map.day}`}
function heat(x){const s=norm(x.status);if(/negociação|contraproposta|orçamento|budget|pré-seleção|aprovado|procurement|contrato|fechado/.test(s))return'hot';if(/resposta humana|interesse|material solicitado|material enviado|encaminhado|contato compartilhado|e-mail recebido|formulário recebido/.test(s))return'warm';return'cold'}
function stageGroup(x){const s=norm(x.status);if(/negocia|orçamento|budget|pré-sele|aprovado|contrato|fechado/.test(s))return'Negociação';if(/material|proposta|formulário/.test(s))return'Material';if(/resposta humana|contato compartilhado|e-mail recebido|encaminhado/.test(s))return'Contato ativo';return'Abertura'}
function DealCard({item}){const context={kind:'opportunity',title:item.title,organization:item.organization||item.brand||item.title,status:item.status,summary:item.summary,nextAction:item.nextAction,events:item.history||[],evidence:item.evidence||[],provenance:item.provenance,sourceArea:'Pipeline'};return <article className="dealCard" data-heat={heat(item)} data-human-edit-card="1" data-native-context="1"><div className="dealTop"><span>{item.market||'BR'} · {item.segment||'comercial'}</span><b>{item.priority||'P2'}</b></div><h3>{item.title}</h3><p>{item.status}</p><section><small>PRÓXIMO MOVIMENTO</small><strong>{item.nextAction}</strong></section><footer><span>{item.lastInteraction||'sem data'}</span><span>{item.provenance||'MUNDO'}</span></footer><div className="dealActions"><ContextOpenButton context={context}/><Link href={'/os/pipeline/'+item.slug}>Abrir ficha</Link><Link href={'/os/propostas?context='+encodeURIComponent(item.organization||item.brand||item.title)}>Gerar proposta</Link></div></article>}
function PipelineStageBoard({rows=[]}){
 const stages=['Negociação','Material','Contato ativo','Abertura'];
 return <section className="pipelineStageBoard" aria-label="Stage board do Pipeline"><header><div><small>STAGE BOARD · HISTÓRIA COMERCIAL VIVA</small><h2>Estágio, próxima ação e evidência no mesmo quadro.</h2></div><span>{rows.length} oportunidades ativas</span></header><div className="stageBoardGrid">{stages.map(stage=>{const items=rows.filter(x=>stageGroup(x)===stage);return <article key={stage}><header><b>{stage}</b><span>{items.length}</span></header><div>{items.slice(0,7).map(item=><Link key={item.slug} href={'/os/pipeline/'+item.slug}><strong>{item.title}</strong><small>{item.status}</small><p>{item.nextAction||'sem próximo movimento materializado'}</p><em>{item.lastInteraction||'sem data'} · {item.provenance||'MUNDO'}</em></Link>)}</div></article>})}</div></section>
}

function FollowupCard({item}){const context={kind:'opportunity',title:item.title,status:item.status,summary:item.summary,nextAction:item.nextAction,events:item.history||[],provenance:item.provenance,sourceArea:'Pipeline'};return <article className="followCard" data-human-edit-card="1" data-native-context="1"><div><small>{item.market||'BR'} · {item.priority||'P2'}</small><b>{item.title}</b><span>{item.status}</span></div><div><strong>{item.nextActionDate||'sem data'}</strong><p>{item.nextAction}</p></div><div className="dealActions"><ContextOpenButton context={context}/><Link href={'/os/pipeline/'+item.slug}>Abrir ficha</Link></div></article>}
export default function PipelineLive({email,projection,todayKey}){
 const[q,setQ]=useState(''),[view,setView]=useState('pipeline'),[expanded,setExpanded]=useState(false);
 const rows=useMemo(()=>{const projected=projection?.currentCards?.length?projection.currentCards:(projection?.operational?.pipeline||projection?.cards||[]);const primary=projected?.length?projected:(CRM_OPERATIONAL_SNAPSHOT.pipeline||[]);return [...primary].filter(x=>!INACTIVE.test(norm(x.status)))},[projection]);
 const followups=useMemo(()=>{const projected=projection?.operational?.followups||[];return projected.length?[...projected]:[...(CRM_OPERATIONAL_SNAPSHOT.followups||[])]},[projection]);
 const filtered=rows.filter(x=>`${x.title} ${x.status} ${x.summary} ${x.nextAction} ${x.owner} ${x.segment}`.toLowerCase().includes(q.toLowerCase()));
 const visibleDeals=expanded?filtered:filtered.slice(0,12);
 const visibleFollowups=expanded?followups:followups.slice(0,12);
 const groups=['Negociação','Material','Contato ativo','Abertura'].map(label=>({label,value:rows.filter(x=>stageGroup(x)===label).length}));
 const heatItems=['hot','warm','cold'].map(label=>({label:label.toUpperCase(),value:rows.filter(x=>heat(x)===label).length}));
 const dueNow=followups.filter(x=>normalizedDateKey(x.nextActionDate)===todayKey).length;
 const hotCount=rows.filter(x=>heat(x)==='hot').length,warmCount=rows.filter(x=>heat(x)==='warm').length;
 const financeSignals=rows.filter(x=>/budget|orçamento|financeiro|pagamento|fee|valor|custo|verba/i.test(`${x.status||''} ${x.summary||''} ${x.nextAction||''}`));
 const procurementSignals=rows.filter(x=>/procurement|compras|fornecedor|cadastro|vendor|contrato|jurídico/i.test(`${x.status||''} ${x.summary||''} ${x.nextAction||''}`));
 return <><main className="pipe resetPipeline" data-visual-reset="mundo-visual-reset-v1" data-area-mode="board-timeline">
 <header className="hero editorialHero"><div><small>PIPELINE · COMERCIAL</small><h1>Negócios em movimento.</h1><p>Agora o Pipeline usa a fila operacional atual: oportunidade, estágio, evidência, próximo movimento e follow-up no mesmo lugar.</p></div><div className="user">{email}</div></header>
 <DataGapHeartbeat surface="pipeline"/>
 <section className="pipelinePulse"><article><b>{rows.length}</b><span>oportunidades ativas</span></article><article><b>{followups.length}</b><span>follow-ups materializados</span></article><article><b>{financeSignals.length}</b><span>sinais financeiro/budget</span></article><article><b>{procurementSignals.length}</b><span>procurement/jurídico</span></article></section>
 <ContextReadingCard area="Pipeline" title="Leitura comercial desta carteira" state={`${rows.length} oportunidades ativas; ${hotCount} quentes e ${warmCount} mornas.`} changed={`${followups.length} follow-ups estão materializados e ${dueNow} caem hoje.`} why="Estágio, evidência e próximo movimento precisam permanecer juntos para não confundir sinal com negociação real." next="Priorize resposta humana, material solicitado, budget, pré-seleção e follow-ups com data antes de novas aberturas frias." source={projection?.source==='mundo-live'?'MUNDO LIVE':'CRM reconciliado'} tone={projection?.source==='mundo-live'?'live':'base'}/>
 <PipelineStageBoard rows={rows}/><section className="chartGrid stageNarrative"><OperationalBarChart title="Distribuição por estágio" items={groups} source={projection?.source==='mundo-live'?'MUNDO LIVE':'CRM reconciliado'} period="carteira atual" updatedAt={projection?.capturedAt||projection?.updatedAt||'leitura atual'} question="Em quais estágios estão as oportunidades ativas?"/><OperationalBarChart title="Temperatura da carteira" eyebrow="INTENSIDADE" items={heatItems} source={projection?.source==='mundo-live'?'MUNDO LIVE':'CRM reconciliado'} period="carteira atual" updatedAt={projection?.capturedAt||projection?.updatedAt||'leitura atual'} question="Qual é a intensidade comercial da carteira ativa?"/></section>
 <section className="pipelineControls"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar marca, estágio, segmento ou próximo movimento…"/><div><button className={view==='pipeline'?'on':''} onClick={()=>setView('pipeline')}>Oportunidades</button><button className={view==='followups'?'on':''} onClick={()=>setView('followups')}>Follow-ups <b>{followups.length}</b></button></div></section>
 {view==='pipeline'?<><section className="dealGrid">{visibleDeals.length?visibleDeals.map(x=><DealCard key={x.slug} item={x}/>):<div className="empty">Nenhuma oportunidade neste recorte.</div>}</section>{filtered.length>12&&<button className="editorialMore" onClick={()=>setExpanded(v=>!v)}>{expanded?'Mostrar recorte executivo':'Ver todas as '+filtered.length+' oportunidades'}</button>}</>:<><section className="followGrid">{visibleFollowups.map(x=><FollowupCard key={x.slug+':'+x.nextActionDate} item={x}/>)}</section>{followups.length>12&&<button className="editorialMore" onClick={()=>setExpanded(v=>!v)}>{expanded?'Mostrar recorte executivo':'Ver todos os '+followups.length+' follow-ups'}</button>}</>}
 <ContextualDivaDock area="Pipeline" context={view==='pipeline'?'oportunidades comerciais atuais':'fila atual de follow-ups'}/>
 </main><style jsx global>{`
 *{box-sizing:border-box}.pipe{max-width:1480px;margin:0 auto;padding:32px clamp(18px,3.4vw,52px) 100px;color:var(--mundo-ink,#211626)}.hero{padding-top:30px!important}.hero small{font-size:9px;font-weight:900;letter-spacing:.14em;color:var(--mundo-signal)}.hero h1{margin:9px 0 12px}.hero p{max-width:780px;color:var(--mundo-muted);font-size:13px;line-height:1.55}.user{font-size:8px;border:1px solid var(--mundo-line);border-radius:999px;padding:8px 10px;height:max-content;background:#fff}
 .pipelinePulse{margin-bottom:28px!important}.pipelinePulse b{display:block;font-size:31px;letter-spacing:-.05em}.pipelinePulse span{font-size:8px;color:var(--mundo-muted)}
 .pipelineStageBoard{margin:24px 0;border-top:1px solid var(--mundo-line);padding-top:20px}.pipelineStageBoard>header{display:flex;justify-content:space-between;gap:16px;align-items:end}.pipelineStageBoard>header small{font-size:8px;font-weight:900;letter-spacing:.13em;color:var(--mundo-signal)}.pipelineStageBoard>header h2{font:400 28px var(--mundo-display,Georgia,serif);margin:5px 0}.pipelineStageBoard>header>span{font-size:8px;color:var(--mundo-muted)}.stageBoardGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--mundo-line);border:1px solid var(--mundo-line);margin-top:14px}.stageBoardGrid>article{background:#fff;min-width:0}.stageBoardGrid>article>header{display:flex;justify-content:space-between;gap:8px;padding:12px;border-bottom:1px solid var(--mundo-line)}.stageBoardGrid>article>header b{font-size:10px}.stageBoardGrid>article>header span{font-size:9px;color:var(--mundo-signal);font-weight:900}.stageBoardGrid a{display:block;padding:12px;border-bottom:1px solid var(--mundo-line);text-decoration:none;color:inherit}.stageBoardGrid a strong,.stageBoardGrid a small,.stageBoardGrid a p,.stageBoardGrid a em{display:block}.stageBoardGrid a strong{font-size:10px}.stageBoardGrid a small{font-size:7px;color:var(--mundo-signal);margin-top:4px}.stageBoardGrid a p{font-size:8px;line-height:1.4;color:var(--mundo-muted);margin:6px 0}.stageBoardGrid a em{font-size:7px;font-style:normal;color:var(--mundo-muted)}.chartGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.pipelineControls{position:sticky;top:70px;z-index:16;display:grid;grid-template-columns:1fr auto;gap:10px;background:rgba(248,245,248,.95);backdrop-filter:blur(14px);padding:14px 0}.pipelineControls input{border:1px solid var(--mundo-line);background:#fff;border-radius:14px;padding:12px}.pipelineControls>div{display:flex}.pipelineControls button{border:1px solid var(--mundo-line);background:#fff;padding:9px 12px;font-size:9px;font-weight:850}.pipelineControls button:first-child{border-radius:999px 0 0 999px}.pipelineControls button:last-child{border-radius:0 999px 999px 0}.pipelineControls button.on{background:var(--mundo-ink);color:#fff}.pipelineControls b{margin-left:5px}
 .dealGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:var(--mundo-line);border:1px solid var(--mundo-line)}.dealCard{position:relative;display:flex;flex-direction:column;min-height:260px;background:#fff;border:1px solid var(--mundo-line);border-radius:0;padding:18px;text-decoration:none;color:inherit;overflow:hidden}.dealCard:before{content:'';position:absolute;left:0;top:0;right:0;height:4px;background:#AEB3BC}.dealCard[data-heat="hot"]:before{background:#E38B22}.dealCard[data-heat="warm"]:before{background:var(--mundo-signal)}.dealTop{display:flex;justify-content:space-between;gap:8px}.dealTop span,.dealTop b{font-size:8px;color:var(--mundo-muted)}.dealTop b{color:var(--mundo-signal)}.dealCard h3{font-size:25px;letter-spacing:-.04em;margin:18px 0 6px}.dealCard>p{font-size:9px;color:var(--mundo-muted);margin:0}.dealCard section{margin-top:auto;padding-top:18px}.dealCard section small{display:block;font-size:7px;font-weight:900;color:var(--mundo-signal);letter-spacing:.1em}.dealCard section strong{display:block;font-size:10px;line-height:1.45;margin-top:6px}.dealCard footer{display:flex;justify-content:space-between;gap:8px;margin-top:15px;padding-top:10px;border-top:1px solid var(--mundo-line);font-size:7px;color:var(--mundo-muted)}.dealActions{display:flex;gap:6px;align-items:center;justify-content:flex-end;margin-top:10px}.dealActions>a{font-size:8px;font-weight:900;color:var(--mundo-signal);text-decoration:none;border:1px solid var(--mundo-line);border-radius:999px;padding:7px 9px;background:#fff}
 .followGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.followCard{display:grid;grid-template-columns:.7fr 1.3fr auto;gap:20px;background:#fff;border:1px solid var(--mundo-line);border-radius:0;padding:16px}.followCard small{font-size:7px;color:var(--mundo-signal);font-weight:900}.followCard b{display:block;font-size:15px;margin:6px 0}.followCard span{font-size:8px;color:var(--mundo-muted)}.followCard strong{font-size:11px}.followCard p{font-size:9px;color:var(--mundo-muted);line-height:1.45;margin:6px 0 0}.editorialMore{display:block;margin:22px auto 0;border:1px solid var(--mundo-line);background:transparent;border-radius:999px;padding:10px 14px;font-size:9px;font-weight:850;color:var(--mundo-signal);cursor:pointer}.empty{grid-column:1/-1;padding:25px;border:1px dashed var(--mundo-line);border-radius:20px;background:#fff;color:var(--mundo-muted)}
 @media(max-width:1050px){.stageBoardGrid{grid-template-columns:1fr 1fr}.dealGrid{grid-template-columns:repeat(2,1fr)}.chartGrid{grid-template-columns:1fr}}@media(max-width:720px){.stageBoardGrid{grid-template-columns:1fr}.pipe{padding:22px 14px 92px}.hero{display:block}.user{display:inline-block;margin-top:8px}.pipelinePulse{grid-template-columns:1fr 1fr}.pipelineControls{grid-template-columns:1fr;top:62px}.dealGrid,.followGrid{grid-template-columns:1fr}.followCard{grid-template-columns:1fr}}
 `}</style></>}
export async function getServerSideProps(ctx){const auth=requireOSAuth(ctx.req);if(auth.redirect)return auth;let live={status:'unavailable',reason:'pipeline_live_not_loaded'};try{live=await getWixLiveBrainContext({force:true})}catch(error){console.error('PIPELINE_LIVE_FALLBACK',String(error?.message||error).slice(0,240))}const projection=buildMundoCommercialProjection({live});return{props:{...auth.props,projection:JSON.parse(JSON.stringify(projection)),todayKey:saoPauloDateKey()}}}
